name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint-bash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Lint shell scripts
        run: |
          shopt -s nullglob
          files=(automation/*.sh)
          if [ ${#files[@]} -gt 0 ]; then
            shellcheck "${files[@]}"
          else
            echo "No shell scripts to lint."
          fi
